# Generated by Django 2.1.5 on 2019-03-03 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrimaryGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Primary Group name, like:425', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PrimaryGroupPrimaryLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.PrimaryGroup')),
            ],
        ),
        migrations.CreateModel(
            name='PrimaryLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Lesson name, like: Math', max_length=50)),
                ('lesson_kind', models.CharField(choices=[('lesson', 'lesson'), ('lecture', 'lecture')], default='lesson', help_text='Lesson kind: lesson or lecture; lesson is default', max_length=7)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('date', models.DateField()),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_kind', models.CharField(choices=[('teacher', 'teacher'), ('student', 'student')], default='student', help_text='Account kind: teacher or student; student is default', max_length=7)),
                ('first_name', models.CharField(blank=True, help_text='Account first name', max_length=40, verbose_name='first name')),
                ('middle_name', models.CharField(blank=True, help_text='Account middle name', max_length=40, verbose_name='middle name')),
                ('last_name', models.CharField(blank=True, help_text='Account last name', max_length=40, verbose_name='last name')),
                ('primary_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.PrimaryGroup')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='primarygroupprimarylesson',
            name='primary_lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.PrimaryLesson'),
        ),
    ]
