# Generated by Django 2.1.5 on 2019-03-11 22:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Group name', max_length=40, verbose_name='name')),
                ('is_primary', models.BooleanField(default=False, help_text='Indicates is the group primary', verbose_name='is_verified')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, help_text='Account first name', max_length=40, verbose_name='first name')),
                ('middle_name', models.CharField(blank=True, help_text='Account middle name', max_length=40, verbose_name='middle name')),
                ('last_name', models.CharField(blank=True, help_text='Account last name', max_length=40, verbose_name='last name')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Group')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, help_text='Account first name', max_length=40, verbose_name='first_name')),
                ('middle_name', models.CharField(blank=True, help_text='Account middle name', max_length=40, verbose_name='middle_name')),
                ('last_name', models.CharField(blank=True, help_text='Account last name', max_length=40, verbose_name='middle_name')),
                ('is_verified', models.BooleanField(default=False, help_text='Indicates teacher has been verified for identity', verbose_name='is_verified')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
